#!/bin/sh
DAEMON=/usr/sbin/hostapd
NAME=hostapd
DESC="HOSTAP Daemon"
ARGS="/etc/hostapd.conf -B"

test -f $DAEMON || exit 0

[ -r /etc/default/hostapd ] && . /etc/default/hostapd

set -e

case "$HOSTAPD_ENABLE" in
	[Nn]*)
		exit 0
		;;
esac

if [ -f /sys/class/net/wlan0/address ] && [ -f /etc/hostapd.conf ]
then 
        MACADDR=`sed -e "s/://g" /sys/class/net/wlan0/address`
        SSID=`grep -e "^ssid" /etc/hostapd.conf | tail -1`
        if [ none$SSID != "none" ]
        then
                cat /etc/hostapd.conf > /run/hostapd.conf
                echo "$SSID-$MACADDR" >> /run/hostapd.conf
                ARGS="/run/hostapd.conf -B"
        fi
fi

case "$1" in
    start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -x $DAEMON -- $ARGS
	echo "$NAME."
	;;
    stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x $DAEMON
	echo "$NAME."
	;;
    restart)
	$0 stop
	$0 start
	;;
    reload)
	echo -n "Reloading $DESC: "
	killall -HUP $(basename ${DAEMON})
	echo "$NAME."
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
	;;
esac

exit 0
